### ISSUE TITLE
Inviting Employees to company without customer_id

### ISSUE THREAD

**Issue by fxmb** [medusajs/b2b-starter-medusa#102]
I am currently implementing a "Teams" section - works amazing so far.

Just one thing: 

I want to be able to invite team members **that are not customers yet**, hence, they do not have a customer_id.

Ideally, there would be a logic (like with slack or elsewhere) that would follow this flow:
1. I invite users by email 
2. user gets an email invite
3. User is saved in employee database but marked as "invite only" => has no account hence no customer id
4. User clicks on invite and registers. Based on email we recognize that this user belongs to the team and we assign them automatically as non admin.

Is this already in place? I will rewrite the code otherwise :-)

**Comment by christiananese** [comment]
Hey @fxmb, really happy everything works good so far.

The functionality you described isn’t currently available and t's not something we have on our immediate roadmap or plan to work on in the foreseeable future.
That said, if you decide to implement a custom solution for this, feel free to share your approach. We'd love to see what you come up with!

Thanks for your feedback!
