### ISSUE TITLE
Redis setup

### ISSUE THREAD

**Issue by brooktewabe** [medusajs/b2b-starter-medusa#109]
Why isn't redis mentioned anywhere, if we should just add it in the config it should be commented out/documented not removed from the medusa.config

redisUrl not found. A fake redis instance will be used.
warn:    Local Event Bus installed. This is not recommended for production.

**Comment by olivermrbl** [comment]
@brooktewabe, you can find a guide for taking Medusa into production in our documentation: https://docs.medusajs.com/learn/deployment/general

It takes you through a proper configuration, including Redis and the Event Bus.
