### ISSUE TITLE
Multi-regional not required

### ISSUE THREAD

**Issue by GXM245** [medusajs/b2b-starter-medusa#113]
Hi team - great work with this repo, the amount of work is truly extraordinary. I was just wondering, we are not in need of multi-region support. Is there a way that this repo can support that without just resorting to activating only one region that permanently has a /cc/ in the URL structure? Conscious that there are many files dependent on region and countryCode props etc.

Thanks

**Comment by olivermrbl** [comment]
@GXM245, do you also only intend to have a single country in that region?

If you want to have a single region with a single country and not have that reflected in the URL structure, you would need to modify the code.
