### ISSUE TITLE
`company` hooks break on admin only dashboards: uses origin to fetch rather than the backend

### ISSUE THREAD

**Issue by JohnGemstone** [medusajs/b2b-starter-medusa#118]
Hi I had some issues deploying this repo on an `admin-only` build since the `companies` hooks fetch directly from `/admin/companies` rather than `[backend_url]/admin/companies`.
https://github.com/medusajs/b2b-starter-medusa/blob/develop/backend/src/admin/hooks/companies.tsx#L30

The `quotes` hooks use the `sdk.client.fetch` method instead and works ok, is there a reason why this pattern wasn't used for the company hooks too?
https://github.com/medusajs/b2b-starter-medusa/blob/develop/backend/src/admin/hooks/api/quotes.tsx#L63

Should I just add the backend url to the fetch, or refactor the hooks to use the sdk?

Cheers!

**Comment by VariableVic** [comment]
Hey @JohnGemstone,

Thanks for reporting this! Nicest solution would be to indeed refactor to the `sdk.client.fetch` method. Would you be up to opening a PR?

**Comment by JohnGemstone** [comment]
Cheers Vic, will take a look this week. For now I fixed with prefixing the endpoint to the url like so:

```ts
let MEDUSA_BACKEND_URL = ""

if (import.meta.env.VITE_MEDUSA_BACKEND_URL) {
  MEDUSA_BACKEND_URL = import.meta.env.VITE_MEDUSA_BACKEND_URL
}

// ...

  useEffect(() => {
    const fetchCompanies = async () => {
      try {
        const response = await fetch(
          `${MEDUSA_BACKEND_URL}/admin/companies` +
            (filterQuery ? `?${filterQuery}` : ""),
          {
            method: "GET",
            credentials: "include", // additional header for CORS
          }
        );
        const result = await response.json();
        setData(result);
      } catch (err) {
        setError(
          err instanceof Error ? err : new Error("An unknown error occurred")
        );
        throw err;
      } finally {
        setLoading(false);
      }
    };

    fetchCompanies();
  }, [refetchTrigger]);
  
  
```

I had trouble figuring out how to use env vars within the dashboard client so may add something to the docs regarding Vite's method for importing them: https://vite.dev/guide/env-and-mode

**Comment by JohnGemstone** [comment]
Refactored by @VariableVic thanks! 
https://github.com/medusajs/b2b-starter-medusa/commit/5bc80385f4d07ec1f8ebd2bab7d4bc386bca0dea
