### ISSUE TITLE
I followed the instructions in the documentation to install the project, but it failed to run.

### ISSUE THREAD

**Issue by ziming012** [medusajs/b2b-starter-medusa#119]
The error is as follows:

error:   Error running script
error:   Workflow with id "update-order-workflow" and step definition already exists.

**Comment by sradevski** [comment]
@ziming012 you likely have 2 different versions of Medusa in your node modules. 

What steps exactly did you follow?

**Comment by alphaklp** [comment]
I have the same issue - clean install - the b2b-starter has a update-order-workflow locally - and it looks like when the std medusa tried to instantiate - the local has already installed the workflow - and the startup fails. 
if I rename the workflow in the local b2b starter to a different name like

export const updateOrderWorkflow = createWorkflow(
  "update-order-workflow2",
  function (input: { id: string; is_d

the server starts

**Comment by sradevski** [comment]
Ok thanks the the details @alphaklp we'll look into it.
