### ISSUE TITLE
Facing some issue during setup backend 

### ISSUE THREAD

**Issue by MohdWaseem789** [medusajs/b2b-starter-medusa#126]
I have follow all the steps but when i run yarn seed facing this error
![Screenshot 2024-12-10 151520](https://github.com/user-attachments/assets/9c24ed9c-2204-4442-8476-4d835ac83f2e)

**Comment by fxmb** [comment]
I saw that there was a commit recently where they deduplicate the workflows (not sure thoough). Try to pull the current version of the repo and try again maybe?

**Comment by fxmb** [comment]
https://github.com/medusajs/b2b-starter-medusa/commit/1eb7cc6d352621efb1981327a9cb83550980b41c

This one covers it I believe

**Comment by MohdWaseem789** [comment]
Thanks now working fine
