### ISSUE TITLE
`query.graph` typing issue

### ISSUE THREAD

**Issue by michael-land** [medusajs/b2b-starter-medusa#128]
Hi,

I'm trying out this template and encountering an error when copying the REST API.

In the src/api/admin/companies/[id]/employees/route.ts API route, this repository has the following definition:

```ts
  const { data: employees, metadata } = await query.graph(
    {
      entity: 'employee',
      fields: req.remoteQueryConfig.fields,
      filters: {
        company_id: id,
        ...req.filterableFields,
      },
    },
    { throwIfKeyNotFound: true }
  );
```

However, the generated types do not include a company_id field for some reason.

![CleanShot 2024-12-10 at 14 46 08@2x](https://github.com/user-attachments/assets/b219772d-9771-4dbf-b0ab-607c3b18b3bd)

I'm still new here, and any help is appreciated. In the documentation, I can't find anything related to this auto-generated type.

**Comment by sradevski** [comment]
Please refer to these docs on how to filter links: https://docs.medusajs.com/learn/fundamentals/module-links/query#apply-filters

You can also see an example of a different approach here: https://github.com/medusajs/medusa/blob/dc5e73af4d2fe4eed8239660d74af6cd2a0994cd/packages/medusa/src/api/store/products/middlewares.ts#L33

**Comment by michael-land** [comment]
Hi @sradevski, thanks for the quick response! The reference code is helpful. However, I have a concern about the generated typing for the custom model.

Here’s the code defining the Employee model:

```ts
export const Employee = model.define('employee', {
  id: model.id({ prefix: 'emp' }).primaryKey(),
  spending_limit: model.bigNumber().default(0),
  is_admin: model.boolean().default(false),

  company: model.belongsTo(() => Company, {
    mappedBy: 'employees',
  }),
});
```

And the corresponding database DML:

```sql
CREATE TABLE public.employee
(
    id                 text                                   NOT NULL
        PRIMARY KEY,
    spending_limit     numeric                  DEFAULT 0     NOT NULL,
    is_admin           boolean                  DEFAULT FALSE NOT NULL,
    company_id         text                                   NOT NULL
        CONSTRAINT employee_company_id_foreign
            REFERENCES public.company
            ON UPDATE CASCADE,
    raw_spending_limit jsonb                                  NOT NULL,
    created_at         timestamp WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at         timestamp WITH TIME ZONE DEFAULT NOW() NOT NULL,
    deleted_at         timestamp WITH TIME ZONE
);
```

Here’s the auto-generated typing for this model (from .medusa/types/remote-query-entry-points.d.ts):

```ts
export type Employee = {
  __typename?: 'Employee';
  id: Scalars['ID']['output'];
  spending_limit: Scalars['String']['output'];
  is_admin: Scalars['Boolean']['output'];
  company: Company;
  raw_spending_limit: Scalars['JSON']['output'];
  created_at: Scalars['DateTime']['output'];
  updated_at: Scalars['DateTime']['output'];
  deleted_at: Maybe<Scalars['DateTime']['output']>;
  customer_link: Maybe<LinkCompanyEmployeeCustomerCustomer>;
};
```

As you can see, the generated type includes only company but not company_id. How can I adjust the model definition, so the generated typing to include a company_id field?

In the core model example with MikroORM, e.g. in the shipping-option model, https://github.com/medusajs/medusa/blob/376b9e85bcce7923f702f822a4e4b36302eb4a42/packages/modules/fulfillment/src/models/shipping-option.ts#L100. Both shipping_profile_id and shipping_profile were generated in type. I’d like something similar for the company and company_id.


![CleanShot 2024-12-11 at 11 18 30@2x](https://github.com/user-attachments/assets/70ebbe29-268e-4c20-880f-80b75d538b4f)
