### ISSUE TITLE
No access to the storefront locally

### ISSUE THREAD

**Issue by rida-rechrache** [medusajs/b2b-starter-medusa#31]
Hello,
Previously, the project was working fine on my local environment, but after the structural changes with Turborepo, I can no longer access it locally.

![image](https://github.com/user-attachments/assets/0049bd61-ca28-4857-bd27-c7dc2562517f)

![image](https://github.com/user-attachments/assets/1373e76b-9c97-4dbd-968b-5bbaf4fea378)

I think you shoud editing app/page.tsx

**Comment by riqwan** [comment]
hey @rida-rechrache, can you share how to reproduce this?

Generally, if you do the following it should work:

1. go to root of the monorepo
2. yarn install
3. yarn dev

It should start server & storefront. Additionally, ensure that you have atleast yarn 3

**Comment by rida-rechrache** [comment]
@riqwan yes, it's solved with yarn version 3.
Thank you :)

**Comment by riqwan** [comment]
Thanks! Will make the repo require yarn 3 before launch. 🎉
