### ISSUE TITLE
Error during yarn setup-db

### ISSUE THREAD

**Issue by chrislicodes** [medusajs/b2b-starter-medusa#47]
Hey, I have trouble setting up the app locally as stated in the README - I am using the versions mentioned there (besides yarn 3.5 I used 4.5 as its in the package.json - probably a typo?)

I've created a db with 

`docker run --name medusa-db -e POSTGRES_USER=myuser -e POSTGRES_PASSWORD=mypassword -e POSTGRES_DB=medusa -p 5432:5432 -d postgres:15`

and then followed the steps in the readme until `yarn setup-db`. The error I receive is:

```bash
yarn setup-db
npm warn config ignoring workspace config at /Users/chris/Projects/medusa/examples/b2b-starter-medusa/apps/backend/.npmrc
? Enter the database name medusa-backend (<- it doesn't matter which name I put here)
error:   Unable to establish database connection because of the following error
error:   SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string
```

I cannot figure out where to put that information - any Idea what I can do? 🤔

**Comment by CosAnca** [comment]
I got stuck on this step as well. Running `yarn setup-db` produces the same error for me.

**Comment by rida-rechrache** [comment]
Hello @CosAnca @chrislicodes,
to fix this problem , you should create your database with the following information:
Database name: medusa-backend
User: postgres
Password: 
Otherwise, edit this key DATABASE_URL with your information :
DATABASE_URL=postgres://user_name:password@localhost/database_name

**Comment by chrislicodes** [comment]
Hi @rida-rechrache, thanks for the reply - I tried that as well some days ago but encountered another error. Today I reinstalled everything and now it is working again. @CosAnca - it should work either way, but this is my env now:

```
STORE_CORS=http://localhost:8000,https://docs.medusajs.com
ADMIN_CORS=http://localhost:7000,http://localhost:7001,https://docs.medusajs.com
AUTH_CORS=http://localhost:7000,http://localhost:7001,https://docs.medusajs.com
REDIS_URL=redis://localhost:6379
JWT_SECRET=supersecret
COOKIE_SECRET=supersecret
DATABASE_URL=postgres://postgres:postgres@localhost/$DB_NAME
DB_NAME=medusa-backend
```
with

```bash
docker run --name medusa-backend -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=medusa-backend -p 5432:5432 -d postgres
```

**Comment by bmad-221B** [comment]
Hi @chrislicodes i am facing the same issue, I have also tried what you did, but the issue remains. Can you please suggest me some things you tried out. Thanks.
