### ISSUE TITLE
font color issue in light mode

### ISSUE THREAD

**Issue by SmartDever02** [medusajs/b2b-starter-medusa#72]
![image](https://github.com/user-attachments/assets/be177329-7d9b-4a2f-b47a-ac32cfcfa580)

**Comment by VariableVic** [comment]
Hey @SmartDever02, I'm unable to reproduce this. What browser are you using? 

![Screenshot 2024-11-05 at 11 34 29](https://github.com/user-attachments/assets/baab14ee-f797-414c-b1aa-abda34d9613f)

**Comment by SmartDever02** [comment]
I am using chrome browser - iirc this happened when I tried to switch dark/light mode in the different page and then come back to this page again.

**Comment by MohdWaseem789** [comment]
Hii @VariableVic @SmartDever02 
I got stuck in the mid I have cloned the b2b starter template and configured everything but when I open admin it says wrong email and password that you provide also publishable key is wrong how we can generate new publishable key and use please help me out

**Comment by VariableVic** [comment]
@MohdWaseem789 you can create a new admin user by running `npx medusa user -e some@email.com -p some-password` and then create a new publishable key from the settings.

Please don't hijack issues in the future, just create an issue or a question in Discussions.

**Comment by MohdWaseem789** [comment]
@VariableVic Thanks a lot it's working fine but products are not there in admin so I can't see in the store can you provide a guideline how we can add product and description all that if you can provide some products we can test it 
Again thanks for the help and reply really appreciate

**Comment by riqwan** [comment]
Feel free to reopen this if this is still an issue @SmartDever02

**Comment by SmartDever02** [comment]
@riqwan if you can share your pr as I don't see any changes in the [website](https://medusa-b2b-starter.vercel.app/dk)

**Comment by riqwan** [comment]
@SmartDever02 cache refresh the page, should be there now

**Comment by SmartDever02** [comment]
> @SmartDever02 cache refresh the page, should be there now

Obviously I tested in the guest mode
