### ISSUE TITLE
Functionality between Orders and Quotes not working as expected

### ISSUE THREAD

**Issue by juanzgc** [medusajs/b2b-starter-medusa#74]
After testing the `b2b-starter-medusa` I've ran across the following issues:

- Admin Quote page doesn't open the individual quote view, which therefore doesn't allow for accepting a quote or updating the value.
- Creation of a quote becomes duplicated and immediately creates the order (duplicated as well)
- Creation of Order doesn't appear in the company's orders, however it does appear in the Admin order's.
- Upon creation of an order that doesn't appear in company's order, it also doesn't discount from the employee's spending limit.

Recording:
https://www.loom.com/share/583109ba23c8454bb927abb619e902fd

```bash
➜  node -v
v20.3.0
➜  yarn --version
4.5.1
➜  turbo --version
2.2.3
```

**Comment by rida-rechrache** [comment]
@juanzgc I have seen this behavior too

**Comment by lexvz14** [comment]
Updating medusa packages to 2.0.3 solved the first issue for me, quoteId route not being visible. It works in 2.0.3.

**Comment by riqwan** [comment]
Hey, these issues have been fixed in the latest develop. Feel free to reopen this if they're still an issue! 🍻
