### ISSUE TITLE
MedusaJS2 Deployment - Admin Panel Stuck on `localhost` URL After Changing Backend URL

### ISSUE THREAD

**Issue by black-spidera** [medusajs/b2b-starter-medusa#76]
Hello,

I’m deploying a MedusaJS2 project and am running into an issue with the admin panel login. Despite updating the backend URL in the `.env` file and even hard-coding my domain name where `localhost:9000` was used, it still defaults to `http://localhost:9000/auth/user/emailpass`.

I've already tried restarting the server and clearing any relevant cache, but nothing seems to work. Has anyone faced this issue before, or does anyone have suggestions on how to ensure the admin panel uses my domain URL instead of defaulting to localhost?

Thanks in advance!

<img width="1470" alt="Screenshot 2024-10-30 at 8 54 42 PM" src="https://github.com/user-attachments/assets/1d0f63e5-97c1-45de-9eda-4087d2091027">

<img width="1470" alt="Screenshot 2024-10-30 at 8 54 31 PM" src="https://github.com/user-attachments/assets/8dd84712-6c35-4001-8e38-9c76fc683e8d">

**Comment by waseem870** [comment]
i am also stuck in this step the provide publish key is not valid how we can reset or create a new one publish key if you found any solution please help me out

**Comment by riqwan** [comment]
@black-spidera, @Satwikloka - The config for the sdk is set here - `apps/storefront/src/lib/config.ts`, can you log the `MEDUSA_BACKEND_URL` and `process.env.NEXT_PUBLIC_MEDUSA_BACKEND_URL` to see what you're getting?

**Comment by princessfrombabylon99** [comment]
@black-spidera Could you try to add your IP address in CORS

**Comment by riqwan** [comment]
Closing this, feel free to reopen if this is still an issue
