### ISSUE TITLE
Adding new quote

### ISSUE THREAD

**Issue by alphaklp** [medusajs/b2b-starter-medusa#77]
When I add a new quote from the cart - I get two quotes created for a single "request for quote" action. 
Looking in the frontend log - it looks like the frontend calls the POST /store/quotes API twice after another.

medusa-next:dev:
medusa-next:dev: Performing request to:
medusa-next:dev:  URL: http://localhost:9000/store/quotes
medusa-next:dev:  Headers: {
medusa-next:dev:   "accept": "application/json",
medusa-next:dev:   "authorization": "<REDACTED>",
medusa-next:dev:   "content-type": "application/json",
medusa-next:dev:   "x-publishable-api-key": "pk_543e122aecfede6ea965f3579dbe913fa6b80301a0d1207f86add0ae42ca8566"
medusa-next:dev: }
medusa-next:dev:
medusa-starter-default:dev: http:    POST /store/quotes ← - (200) - 731.482 ms
medusa-next:dev: Received response with status 200
medusa-next:dev:
medusa-next:dev:  POST /dk/cart 200 in 1225ms
medusa-next:dev: Performing request to:
medusa-next:dev:  URL: http://localhost:9000/store/quotes
medusa-next:dev:  Headers: {
medusa-next:dev:   "accept": "application/json",
medusa-next:dev:   "authorization": "<REDACTED>",
medusa-next:dev:   "content-type": "application/json",
medusa-next:dev:   "x-publishable-api-key": "pk_543e122aecfede6ea965f3579dbe913fa6b80301a0d1207f86add0ae42ca8566"
medusa-next:dev: }
medusa-next:dev:
medusa-starter-default:dev: http:    POST /store/quotes ← - (200) - 323.399 ms
medusa-next:dev: Received response with status 200
medusa-next:dev:
medusa-next:dev:  POST /dk/cart 200 in 364ms
medusa-next:dev:  ○ Compiling /[countryCode]/account/quotes/details/[id] ...
medusa-next:dev:  ✓ Compiled /[countryCode]/account/quotes/details/[id] in 2.7s (3962 modules)
medusa-next:dev: Initiating Medusa client with default headers:
medusa-next:dev:  {
medusa-next:dev:   "accept": "application/json",
medusa-next:dev:   "content-type": "application/json",
medusa-next:dev:   "x-publishable-api-key": "pk_543e122aecfede6ea965f3579dbe913fa6b80301a0d1207f86add0ae42ca8566",
medusa-next:dev:   "authorization": "<REDACTED>"
medusa-next:dev: }
medusa-next:dev:
medusa-next:dev: Performing request to:
medusa-next:dev:  URL: http://localhost:9000/store/customers/me?fields=%2Aemployee%2C%20%2Aorders
medusa-next:dev:  Headers: {
medusa-next:dev:   "accept": "application/json",
medusa-next:dev:   "authorization": "<REDACTED>",
medusa-next:dev:   "content-type": "application/json",
medusa-next:dev:   "next": "[object Object]",
medusa-next:dev:   "x-publishable-api-key": "pk_543e122aecfede6ea965f3579dbe913fa6b80301a0d1207f86add0ae42ca8566"
medusa-next:dev: }
medusa-next:dev:
medusa-starter-default:dev: http:    GET /store/customers/me?fields=%2Aemployee%2C%20%2Aorders ← - (200) - 128.173 ms
medusa-next:dev: Received response with status 200
medusa-next:dev:
medusa-next:dev: Performing request to:
medusa-next:dev:  URL: http://localhost:9000/store/quotes/quo_01JBYC13K0DMFW9XAAH3AMJJSC
medusa-next:dev:  Headers: {
medusa-next:dev:   "accept": "application/json",
medusa-next:dev:   "authorization": "<REDACTED>",
medusa-next:dev:   "content-type": "application/json",
medusa-next:dev:   "next": "[object Object]",
medusa-next:dev:   "x-publishable-api-key": "pk_543e122aecfede6ea965f3579dbe913fa6b80301a0d1207f86add0ae42ca8566"
medusa-next:dev: }
medusa-next:dev:

**Comment by MohdWaseem789** [comment]
@alphaklp did you find solution of that if yes please share with me I also got stuck also I am not able to open quote request from the admin to see the details of quote

**Comment by alphaklp** [comment]
Hi Mohd

no - i was trying to debug it earlier today - but did not find enough time. I will post on the issues if I find some (or maybe get a pullrequest into the repo)





Venlig hilsen/Best Regards



Klaus Petersen

+45 22 69 59 60

***@***.******@***.***>


This message including any attachments may contain confidential and/or privileged information
intended only for the person or entity to which it is addressed. If you are not the intended recipient,
you should delete this message. Any printing, copying, distribution or other use of this message is strictly prohibited.
If you have received this message in error, please notify the sender immediately by telephone
or e-mail and delete all copies of this message and any attachments from your system. Thank you.







________________________________

**Comment by MohdWaseem789** [comment]
Ok thanks for reply once you find solution for that please let me know really appreciate

**Comment by riqwan** [comment]
Hey guys, this has been fixed in the latest develop. Let me know if that solves it! @MohdWaseem789 @alphaklp

**Comment by riqwan** [comment]
Closing this for now, reopen if this still persists.
