### ISSUE TITLE
installing b2b starter on windows

### ISSUE THREAD

**Issue by alphaklp** [medusajs/b2b-starter-medusa#78]
Installing on a pure windows box fails. 
The package command "generate-env" fails due to the cp copy command.

I also experienced that the postgres database required a "admin" database (same name as my user - dont know if it is a coincidence) - could not setup the database until I manually created this database (just an empty db) - this is potentially the database it connects to, to be able to create the "medusa-backend" database.

**Comment by riqwan** [comment]
Since we don't have that command anymore and falling back to a bare knucle setup of medusa, this should no longer be an issue. Feel free to reopen if this persists.
