### ISSUE TITLE
Unsupported Protocol 'workspace:^' in Dependencies Causing Deployment Failure on DigitalOcean

### ISSUE THREAD

**Issue by PavanKalisetti** [medusajs/b2b-starter-medusa#85]
I'm encountering a build error when deploying my MedusaJS project on DigitalOcean due to the use of workspace:^ in my dependencies. The build fails because npm doesn't fully support workspace protocols, which are required by Yarn. Additionally, my package.json specifies engines.node with >=20, but DigitalOcean's build system interprets this as an ambiguous version, leading to further issues.

**Error Message:**
`npm error Unsupported URL Type "workspace:": workspace:^`

Deployment Platform: DigitalOcean
Node Version Specified: >=20

![Screenshot 2024-11-12 064125](https://github.com/user-attachments/assets/26a0cd26-ac31-471a-a736-764e680276bd)

**Comment by Satwikloka** [comment]
Hi @riqwan ,
I am facing same issue Please take up this issue and help me to deploy the B2B starter.
