### ISSUE TITLE
yarn start not working

### ISSUE THREAD

**Issue by brooktewabe** [medusajs/b2b-starter-medusa#89]
I am just setting up this app and yarn dev works fine but yarn start returns
**missing tasks in project
 could not find task `start` in project**
 
 What does this mean if anyone has any idea?

**Comment by sradevski** [comment]
Please see https://docs.medusajs.com/learn/build on how to run production builds

**Comment by mk0y** [comment]
I'm also curious about this, and I'm not really following where to run `npx medusa build` command? If I run it from `apps/backend` I will be getting `Cannot find module '@starter/types' or its corresponding type declarations.`.
And from root it won't work, there's no tsconfig.json file.

**Comment by mk0y** [comment]
You need `"start": {}` in turbo.json even if it's empty, and (with optional filter) `npx turbo run start -- --filter=backend` if you want to start only backend. These is basic stuff for deployment, should be documented.
