### ISSUE TITLE
Not responsive

### ISSUE THREAD

**Issue by princessfrombabylon99** [medusajs/b2b-starter-medusa#91]
On mobile, the price widget is not responsive.

![IMG_5917](https://github.com/user-attachments/assets/c65e0763-f984-475c-8649-69b5a00d3ae8)

**Comment by christiananese** [comment]
Hey @princessfrombabylon99, thank you for filling out the issue. 😊 

What behavior would you expect? The table was intentionally designed to be horizontally scrollable.

I'll close the issue, but feel free to open a PR with an alternative solution.

**Comment by princessfrombabylon99** [comment]
Okay
