### ISSUE TITLE
Router context issue on admin for quotes and companies

### ISSUE THREAD

**Issue by fxmb** [medusajs/b2b-starter-medusa#99]
<img width="1800" alt="image" src="https://github.com/user-attachments/assets/de2c1c58-166d-4392-b544-33e914ec47c5">
Have above error and in the logs it says this:

<img width="607" alt="image" src="https://github.com/user-attachments/assets/f95feada-d53e-41fe-a760-912cc47a214a">

Seems to be an error with Router context. How come this happened all of a sudden? Didnt change anything about quotes or companies implementation

**Comment by fxmb** [comment]
Ok I just wrapped the main compoennts in <BrowserRouter> </BrowserRouter> from react and it worked. weird how this works and how would it have worked before?

**Comment by thetutlage** [comment]
Hello @fxmb 👋

Hard to know what's wrong and what should be the solution without looking at any code. I will close this issue for now and feel free to comment back with relevant code/information for us to help further :)
